### ISSUE TITLE
Use asm directly, not vendored clojure.asm

### ISSUE THREAD

**Issue by puredanger** [redplanetlabs/defexception#1]
The clojure.asm namespaces are not considered a public part of the Clojure API. We can, and have, periodically updated it, at times this includes breaking changes inside the ASM library. Because we consider these to be internal, we do not test or guarantee anything about these APIs.

If you wish to use asm, you should depend on the asm library and use the official asm API, not the Clojure library.

**Comment by coreagile** [comment]
This is actually a showstopper for adoption for me, for sure.

**Comment by bhauman** [comment]
I hear your concerns on using the vendored `asm` and weighed it against the trade off of introducing another dependency for such a small library. This library is using and extremely minimal and core set of asm commands which have an extremely minor chance of changing (this library is simply forwarding a constructor) versus the much higher chance of having and `objectweb.asm` dependency collision and I feel I chose correctly in this case, especially for us.  If this is or becomes a problem for consumers it is a simple task to fork and include this one dependency.
