### ISSUE TITLE
Ability to omit stacktrace

### ISSUE THREAD

**Issue by vemv** [redplanetlabs/defexception#15]
Hi! Happy user here.

https://github.com/fmnoise/flow/tree/4.2.1#isnt-using-exceptions-costly describes the mechanism and use case for omitting stack traces - it's something JDK7+ allows.

I wonder if you'd be interested in offering a `defexception` option that allowed to specify a default behavior for that exception class:

```clj
(defexception Foo {:include-stacktraces? true})
```

Thanks - V

**Comment by nathanmarz** [comment]
Interesting idea, but we're just going to keep this library simple for now.
