### ISSUE TITLE
kondo exports

### ISSUE THREAD

**Issue by vemv** [redplanetlabs/defexception#17]
Hey there,

probably you use clj-kondo?

It would be nice if this lib provided exports such that e.g. `(defexception RequestTimeoutException)` didn't later trigger a `error: Unresolved symbol: RequestTimeoutException` in the same namespace.

...Of course, this can be solved locally but a nice default for everyone would be better.

Cheers - V

**Comment by nathanmarz** [comment]
Not going to include this within this project since we want to keep the maintenance overhead as low as possible.
