### ISSUE TITLE
any reason not to use gen-interface to avoid needed a Java class?

### ISSUE THREAD

**Issue by yogthos** [redplanetlabs/defexception#18]
Is there a reason not to use `(gen-interface :name "com.rpl.defexception.IDefException")` in the `impl` namespace instead of having a class that needs to be compiled?

**Comment by nathanmarz** [comment]
What do you mean? An interface isn't sufficient for what this library is doing.

**Comment by yogthos** [comment]
it seems to work with this change, is there something not captured with the tests?
https://github.com/yogthos/defexception/commit/4c13411b309e68b562df529506de421e1043bbdd

**Comment by nathanmarz** [comment]
Ah I see what you're saying. Yea, that's equivalent. There's no particular reason to write that in Java in this case, but it doesn't make much of a difference not to.

**Comment by yogthos** [comment]
Yeah, mostly just avoids the need for Java compilation. I could do a PR if that's welcome.

**Comment by nathanmarz** [comment]
Thanks, but not really worth the hassle of dealing with contributor agreement for such a small refactor.
